### ISSUE TITLE
Request: Bayesian Cluster Ensembles (BCE)

### ISSUE THREAD

**Issue by tsano430** [tsano430/ClusterEnsembles.jl#5]
The Bayesian cluster ensembles (BCE) should also be implemented. 

Reference: H. Wang, H. Shan, and A. Banerjee, "Bayesian cluster ensembles," Statistical Analysis and Data Mining: The ASA Data Science Journal, vol. 4, no. 1, pp. 54-70, 2011.

**Comment by Yifeng-J** [comment]
Hi~
Is there any bug in the MCLA method? I put the labels got from kmeans, spectral clustering and DBSCAN but get the same ARI and V-messure as spectral clustering. This is an accidient or bug?

**Comment by tsano430** [comment]
I'm still in the process of learning about BCE. It will be a long time before I can implement it. So, PR is very welcome.
